<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
		<ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
		<SignAssembly>False</SignAssembly>
		<ErrorReport>none</ErrorReport>
		<IncludeSymbols>False</IncludeSymbols>
		<Version>2.4.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Product>Xpass</Product>
		<Company>ssmmtt</Company>
		<Copyright>Copyright © 2026 ssmmtt</Copyright>
		<Description>Decrypt Xshell session file password.</Description>
	</PropertyGroup>

</Project>
