name: BuildRelease

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete workflows history
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: ./build.ps1

      - name: Get tag description
        id: get_tag_description
        run: |
          $TAG_NAME=$(git describe --tags --exact-match)
          $TAG_DESCRIPTION=$(git show $TAG_NAME --no-patch --format='%b' | Select-Object -Skip 3)
          echo "Tag description: $TAG_DESCRIPTION"
          echo "tag_description=$TAG_DESCRIPTION" >> $env:GITHUB_OUTPUT

      - name: Extract tag name
        id: extract_tag
        run: |
          $TAG_NAME = ${{ github.ref }}.Replace('refs/tags/', '')
          echo "tag_name=$TAG_NAME" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          name: Release ${{ steps.extract_tag.outputs.tag_name }}
          body: ${{ steps.get_tag_description.outputs.tag_description }}
          draft: false
          prerelease: false
          files: |
            ./bin/Xpass/Xpass_x86.exe
            ./bin/Xpass/Xpass_x64.exe
